# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:4.4.0
    ports:
      - 37017:27017
    restart: always

  liquibase-cli-1:
    build: .

  liquibase-cli-2:
    build: .